apiVersion: v2
name: test
version: 0.0.0
dependencies:
  # - name: kube-prometheus-stack
  - name: argo-cd
    # repository: oci://ghcr.io/prometheus-community/charts
    repository: oci://registry-1.docker.io/usmonster
    # version: 59.1.0
    # version: 60.0.0
    version: 50.0.0
